refactor: update test method names
AY2122S2-CS2103T-T17-2/tp pull request #112
Opened 2022-03-18 04:04 UTC by yusufaine

Changes were made with respect to the discussion [here](https://github.com/AY2122S2-CS2103T-T17-2/tp/pull/105#issuecomment-1072001031).

2022-03-18 05:31 UTC, gigituang reviewed
LGTM! i will update the ListCommandTest according

2022-03-18 05:31 UTC, gigituang approved these changes

2022-03-18 05:57 UTC, blaketingyu approved these changes
LGTM! 🌮 I believe you've covered most of the test cases already eg validity, equality.

2022-03-18 06:10 UTC, blaketingyu commented on src/test/java/seedu/address/model/recipe/CompletionTimeTest.java
> +    public void equals_test() {
Just a reminder, if we are standardizing our test method names to be more specific/detailed. Then we should change the equals_test method name.

```suggestion
    public void test_equalityCheckForValidAndInvalidCompletionTime() {
```

2022-03-18 06:14 UTC, blaketingyu commented on src/test/java/seedu/address/model/recipe/CompletionTimeTest.java
> +    public void hashCode_test() {
Maybe this one could be something like
```suggestion
    public void test_equalityCheckForHashCodeOfTheSameObject() {
```

2022-03-18 06:15 UTC, blaketingyu requested changes
Maybe the naming convention could be more specific/detailed as what @aidanaden mentioned. 
The method names I've suggested could be improved as well. It's just a suggestion 🌮 😄

2022-03-20 19:46 UTC, aidanaden approved these changes
LGTM! I don't think equals_test and hashcode_test requires super specific naming conventions considering it's a common test done on all classes.

🔥 🔥 🔥

2022-03-21 02:03 UTC, merged