test: add tests for reset command
AY2122S2-CS2103T-T17-2/tp pull request #143
Opened 2022-03-24 07:12 UTC by blaketingyu

test: add tests for reset command

2022-03-24 08:38 UTC, aidanaden requested changes
Small nits and name suggestions, also changed the nasi lemak sample recipe's incorrect ingredient values.

Otherwise, LGTM! 🍝

2022-03-24 08:38 UTC, aidanaden commented on src/main/java/seedu/address/model/util/SampleDataUtil.java
> +        Ingredient i2 = new Ingredient("rice", 1, "- s cook the rice");
This seems incorrect, Ingredient quantifier should not contain a step

```suggestion
        Ingredient i2 = new Ingredient("rice", 1, null);
```

2022-03-24 08:38 UTC, aidanaden commented on src/main/java/seedu/address/model/util/SampleDataUtil.java
> +        List<Ingredient> ingredients2 = List.of(ingredientArr2);
minor: variable name suggestion

```suggestion
        List<Ingredient> nasiLemakIngredients = List.of(ingredientArr2);
```

2022-03-24 08:38 UTC, aidanaden commented on src/test/java/seedu/address/logic/commands/ClearCommandTest.java
> +    public void execute_showsRequireConfirmationMessage() {
```suggestion
    public void execute_showsRequireConfirmationMessage_success() {
```

2022-03-24 08:38 UTC, aidanaden commented on src/test/java/seedu/address/logic/commands/ResetCommandTest.java
> +    public void execute_showsRequireConfirmationMessage() {
```suggestion
    public void execute_showsRequireConfirmationMessage_success() {
```

2022-03-24 10:08 UTC, aidanaden approved these changes
Just 1 minor question, overall LGTM! 🍝 🍝 🍝  1 more feature to go!!!

2022-03-25 05:34 UTC, yusufaine approved these changes
Changes looks good to me too! Lessssgeddddiiiitt 🔥

2022-03-25 10:26 UTC, merged