fix: ViewCommand and IngredientTest issues
AY2122S2-CS2103T-T17-2/tp pull request #148
Opened 2022-03-24 19:20 UTC by gigituang

2022-03-24 19:24 UTC, yusufaine approved these changes
Left a minor suggestion for how the ingredients would be appended, functionally the same but this just looks _cleaner_.

2022-03-24 19:24 UTC, yusufaine commented on src/main/java/seedu/address/logic/commands/ViewCommand.java
> +                    ingredient.quantity, ingredient.quantifier));
Minor suggestion:

```suggestion
            ingredients.append(String.format("%s\n", ingredient.toString()));
```

2022-03-24 19:32 UTC, aidanaden approved these changes
LGTM! 🍝 🍝 🍝

2022-03-25 02:47 UTC, blaketingyu approved these changes
LGTM 🌮

2022-03-25 05:41 UTC, yusufaine requested changes
As mentioned by @Oddcorner changes to RecipeDisplay.java needs to be made as well as.

2022-03-25 05:53 UTC, yusufaine approved these changes

2022-03-25 06:30 UTC, merged